---
- hosts: all
  gather_facts: no
  tasks:
    - name: Wait for systems to come online
      wait_for_connection:
        delay: 0
        timeout: 300

- hosts: kafka
  roles:
    - prerequisites
    - ssl_generate_keys
  vars_files:
    - vars/global_settings.yml

- hosts: kafka[0]
  roles:
    - ssl_sign_keys
  vars_files:
    - vars/global_settings.yml

- hosts: kafka
  roles:
    - ssl_distribute_keys
    - kafka
  vars_files:
    - vars/global_settings.yml